[mongodb]
mongodb.somaraju.online
[catalogue]
catalogue.somaraju.online
[frontend]
frontend.somaraju.online
[redis]
redis.somaraju.online
[user]
user.somaraju.online
[cart]
cart.somaraju.online
[shipping]
shipping.somaraju.online
[mysql]
mysql.somaraju.online
[payment]
payment.somaraju.online
[rabbitmq]
rabbitmq.somaraju.online

[all:vars]
ansible_user=ec2-user
ansible_password=DevOps321

[localhost]
localhost